# kubectl apply -f app-productos-deplyment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-productos # etiqueta del deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-productos
  template:
    metadata:
      labels:
        app: app-productos
    spec:
      containers:
        - name: app-productos
          image: darkenblue952518/app-productos
          ports:
            # puerto del contenedor
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-productos-service
spec:
  type: ClusterIP
  selector:
    app: app-productos
  ports:
    - protocol: TCP
      # puerto del servicio
      port: 8080
      # puerto del contenedor
      targetPort: 8080